[workspace]
authors = ["Cauch-BS <cachybs@snu.ac.kr>"]
channels = ["conda-forge", "bioconda"]
name = "cscg-hippo"
version = "0.1.0"
platforms = ["linux-64"]

[dependencies]
python = ">=3.11.14,<3.12"
numba = ">=0.63.1,<0.64"
umap-learn = ">=0.5.11,<0.6"
tqdm = ">=4.67.3,<5"
ipykernel = ">=7.1.0,<8"
zarr = "<3"
pandas = "<2"
pip = ">=26.0.1,<27"
h5py = ">=3.15.1,<4"
gcsfs = ">=2026.1.0,<2027"
numpy = "<2"
pyarrow = ">=23.0.0,<24"
