[workspace]
authors = ["Cauch-BS <cachybs@snu.ac.kr>"]
channels = ["conda-forge", "bioconda"]
name = "cscg-hippo"
version = "0.1.0"
platforms = ["linux-64"]

[dependencies]
python = ">=3.14.3,<3.15"
numba = ">=0.63.1,<0.64"
umap-learn = ">=0.5.11,<0.6"
numpy = ">=2.3.5,<3"
pandas = ">=3.0.0,<4"
tqdm = ">=4.67.3,<5"
ipykernel = ">=7.1.0,<8"
